spring:
  datasource:
    url: jdbc:mysql://localhost:3307/sw4booth_dev?serverTimezone=Asia/Seoul&useSSL=false
    username: booth
    password: booth1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
